### PR TITLE
Make stacklock2nix work even if no local packages are specified

### PR DESCRIPTION
**Pull request by cdepillabout**
This is a small improvement to `stacklock2nix` that makes it work even if there are no local `packages` defined in the input `stack.yaml` file.

Fixes https://github.com/cdepillabout/stacklock2nix/issues/49

### CODE REVIEW

**Comment by cdepillabout** [comment]
@chris-martin would you be able to check that this fix works for you in https://github.com/freckle/stack-lint-extra-deps/pull/31?

**Comment by chris-martin** [comment]
This suppresses the error but still ignores the package I'm trying to build (see https://github.com/cdepillabout/stacklock2nix/issues/49#issuecomment-2269991803).

**Comment by cdepillabout** [comment]
@chris-martin I just pushed 25b6944 which should implement the default of a single package in the same directory as the `stack.yaml` file if the `packages` key is missing from `stack.yaml`.

Could you take a look at this and see if it is working for you in https://github.com/freckle/stack-lint-extra-deps/pull/31?

**Comment by cdepillabout** [comment]
I'm going to go ahead and merge this in, since I think it should be working well now.

**Comment by chris-martin** [comment]
(Much belated) thank you, it is working :heart:

**Pull request merged**
