### PR TITLE
Handle old splitmix Haskell package arguments

### LINKED ISSUE #27: Example projects not working
Hi! I'm trying to follow the guide to test the examples provided in the repo, but I'm facing some issues, here's what I've done so far:

1. Fresh clone of the repo
2. Run `nix build` from `my-example-haskell-lib-easy/`. I get this error:
```sh
$ nix build
error: hash mismatch in fixed-output derivation '/nix/store/d6dbmxf60l647hmlfypk409zk1pmg371-source.drv':
         specified: sha256-Hz/xaCoxe4cJBH3h/KIfjzsrEyD915YEVEK8HFR7nO4=
            got:    sha256-ULKUethJNV2/5bs5xMKcPtX3qX10pvyjd5+whVRwVmQ=
error: 1 dependencies of derivation '/nix/store/2il79k0lfzpvjvs97xnn6x0a05asnsls-all-cabal-hashes-component-hspec-2.9.7.drv' failed to build
error: 1 dependencies of derivation '/nix/store/r3bdjfg4yfd87hsjkhm8vhp6j71wl8qi-cabal2nix-hspec-2.9.7.drv' failed to build
(use '--show-trace' to show detailed location information)
```
3. Replace sha256 with the one suggested in the error in [my-example-haskell-lib-easy/flake.nix#L96](https://github.com/cdepillabout/stacklock2nix/blob/8e027606ac4e59498f74024830f8672188ae7bfa/my-example-haskell-lib-easy/flake.nix#L96):
4. At this point, after another `nix build` I get the following (as I originally mentioned in https://github.com/cdepillabout/stacklock2nix/issues/25):
```sh
$ nix build
warning: Git tree '/Users/oizquierdo/sb/stacklock2nix' is dirty
error: anonymous function at /nix/store/r5r86ssz81zdhmasban29996a4fiilq6-cabal2nix-splitmix-0.1.0.4/default.nix:1:1 called with unexpected argument 'testu01'

       at /nix/store/9qkpbm10iypl7zclprk9r0pwncr0snjk-source/pkgs/development/haskell-modules/make-package-set.nix:97:40:

           96|       # this wraps the `drv` function to add a `overrideScope` function to the result.
           97|       drvScope = allArgs: ensureAttrs (drv allArgs) // {
             |                                        ^
           98|         overrideScope = f:
(use '--show-trace' to show detailed location information)
```

Other things I've tried or found:
- `nix flake update`
- Update `all-cabal-hashes` to latest rev
- Compare contents of these two files, which I expected to be the same. 
https://github.com/NixOS/nixpkgs/blob/a4b903646ce5f446877662a851ab1cc206b4d708/pkgs/development/haskell-modules/hackage-packages.nix#L274139-L274157
```sh
$ cat /nix/store/g18qmc2qzdicd2qns729gcpca2sp9v93-cabal2nix-splitmix-0.1.0.4/default.nix
{ mkDerivation, async, base, base-compat, base-compat-batteries
, bytestring, clock, containers, criterion, deepseq, HUnit, lib
, math-functions, process, random, test-framework
, test-framework-hunit, tf-random, vector
}:
mkDerivation {
  pname = "splitmix";
  version = "0.1.0.4";
  sha256 = "6d065402394e7a9117093dbb4530a21342c9b1e2ec509516c8a8d0ffed98ecaa";
  revision = "1";
  editedCabalFile = "1iqlg2d4mybqwzwp67c5a1yxzd47cbp4f7mrpa6d0ckypis2akl0";
  libraryHaskellDepends = [ base deepseq ];
  testHaskellDepends = [
    async base base-compat base-compat-batteries bytestring containers
    deepseq HUnit math-functions process random test-framework
    test-framework-hunit tf-random vector
  ];
  benchmarkHaskellDepends = [
    base clock containers criterion random tf-random
  ];
  description = "Fast Splittable PRNG";
  license = lib.licenses.bsd3;
}
```

### PR DESCRIPTION
**Pull request by cdepillabout**
This PR handles the cabal2nix arguments for splitmix older than 0.1.0.4.

Close #27

### CODE REVIEW

**Comment by oscar-izval** [comment]
Same thing on this branch :(

```sh
$ nix build
error: hash mismatch in fixed-output derivation '/nix/store/2n8dc0z22c7fvmhhvab28hvdwaf7cb3h-source.drv':
         specified: sha256-MLF0Vv2RHai3n7b04JeUchQortm+ikuwSjAzAHWvZJs=
            got:    sha256-WMkGyt1IFBGQzw4vnCouiiAhPa8BXr7cFM30RZsgvLY=
error: 1 dependencies of derivation '/nix/store/gk8s5df4pwr0ckaidi141krrnl7c6xz6-all-cabal-hashes-component-hspec-2.9.7.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qg8hsw58a81ayqmm583i83grqfs970pp-cabal2nix-hspec-2.9.7.drv' failed to build
```

**Comment by cdepillabout** [comment]
@sestrella I've tried to fix the `splitmix` problem on OSX in the most recent commit here (2aaf788).  Could you test this out and let me know if this gets you past the `splitmix`-related problem you had diagnosed in https://github.com/cdepillabout/stacklock2nix/issues/27#issuecomment-1583309973?

@oscar-izval Let's take your problem back to https://github.com/cdepillabout/stacklock2nix/issues/27 and discuss it there.

**Comment by cdepillabout** [comment]
@sestrella Yeah, for now my guess is that https://github.com/NixOS/nixpkgs/issues/39308 is causing you problems.

I actually changed the suggested way to use `all-cabal-hashes` in 

https://github.com/cdepillabout/stacklock2nix/pull/17/files#diff-b23a16eddcabc429456d4365589df781d2b09a3a73a67fe96f1c2c5d58a1da49L49-L52

I'm wondering what would happen if you were to go back to the old way of specifying `all-cabal-hashes` using `fetchurl` instead of `fetchFromGitHub`? I'm guessing you won't see the hash mismatch here, since the the .tar.gz itself is hashed, not its contents.

For example:

```diff
diff --git a/my-example-haskell-lib-easy/flake.nix b/my-example-haskell-lib-easy/flake.nix
index f2b4748..027cef9 100644
--- a/my-example-haskell-lib-easy/flake.nix
+++ b/my-example-haskell-lib-easy/flake.nix
@@ -89,11 +89,9 @@
           #
           # If you are using a very recent Stackage resolver and an old Nixpkgs,
           # it is almost always necessary to override `all-cabal-hashes`.
-          all-cabal-hashes = final.fetchFromGitHub {
-            owner = "commercialhaskell";
-            repo = "all-cabal-hashes";
-            rev = "f3f41d1f11f40be4a0eb6d9fcc3fe5ff62c0f840";
-            sha256 = "sha256-MLF0Vv2RHai3n7b04JeUchQortm+ikuwSjAzAHWvZJs=";
+          all-cabal-hashes = final.fetchurl {
+            url = "https://github.com/commercialhaskell/all-cabal-hashes/archive/f3f41d1f11f40be4a0eb6d9fcc3fe5ff62c0f840.tar.gz";
+            sha256 = "sha256-vYFfZ77fOcOQpAef6VGXlAZBzTe3rjBSS2dDWQQSPUw=";
           };
         };
 
```

I've confirmed locally that on Linux, the hash `sha256-vYFfZ77fOcOQpAef6VGXlAZBzTe3rjBSS2dDWQQSPUw=` is correct.

**Comment by sestrella** [comment]
@cdepillabout replacing `fetchFromGitHub` with `fetchurl` does work, however, I faced an issue running `happy` test suite:


```
last 10 log lines:
> [1 of 1] Compiling Main             ( shift01.agc.hs, shift01.agc.o )
> Linking shift01.agc.bin ...
> --> Checking shift01.agc.bin...
> ./shift01.agc.bin
> make: Target 'all' not remade because of errors.
> rm issue95.agc.hs bug001.a.hs typeclass_monad001.a.hs bug001.gc.hs AttrGrammar001.agc.hs TestMulti.agc.hs issue95.a.hs monaderror-explist.gc.hs monaderror.ag.hs monaderror-explist.a
gc.hs test_rules.agc.hs issue93.agc.hs monad002.ag.hs test_rules.gc.hs Test.gc.hs AttrGrammar002.gc.hs monad001.ag.hs AttrGrammar001.ag.hs typeclass_monad002.ag.hs precedence001.agc.hs typec
lass_monad001.agc.hs typeclass_monad_lexer.gc.hs test_rules.ag.hs bug001.ag.hs issue94.a.hs monad002.agc.hs bug002.gc.hs typeclass_monad001.ag.hs precedence002.a.hs monaderror-explist.ag.hs
issue91.gc.hs bogus-token.ag.hs Test.a.hs monaderror-explist.a.hs rank2.gc.hs typeclass_monad002.a.hs TestMulti.gc.hs typeclass_monad002.gc.hs precedence002.gc.hs issue91.ag.hs bug001.agc.hs
TestPrecedence.gc.hs issue93.gc.hs monad001.a.hs monad002.a.hs typeclass_monad001.gc.hs typeclass_monad_lexer.ag.hs bogus-token.gc.hs rank2.ag.hs TestPrecedence.a.hs rank2.agc.hs issue91.a.
hs TestMulti.ag.hs shift01.ag.hs AttrGrammar002.ag.hs monaderror.agc.hs bug002.agc.hs bogus-token.a.hs Partial.a.hs issue94.gc.hs rank2.a.hs shift01.agc.hs bug002.ag.hs precedence001.ag.hs p
recedence001.a.hs typeclass_monad002.agc.hs Partial.agc.hs bug002.a.hs monad001.gc.hs AttrGrammar001.a.hs issue93.a.hs AttrGrammar002.agc.hs typeclass_monad_lexer.agc.hs monad002.gc.hs prece
dence002.agc.hs issue94.agc.hs monaderror.gc.hs AttrGrammar002.a.hs shift01.gc.hs TestPrecedence.agc.hs issue94.ag.hs typeclass_monad_lexer.a.hs precedence002.ag.hs shift01.a.hs TestPreceden
ce.ag.hs Test.ag.hs issue93.ag.hs bogus-token.agc.hs monaderror.a.hs issue95.ag.hs Partial.gc.hs Partial.ag.hs precedence001.gc.hs Test.agc.hs issue95.gc.hs TestMulti.a.hs AttrGrammar001.gc.
hs test_rules.a.hs monad001.agc.hs issue91.agc.hs
> make: Leaving directory '/private/tmp/nix-build-happy-1.20.0.drv-0/happy-1.20.0/tests'
> Test suite tests: FAIL
> Test suite logged to: dist/test/happy-1.20.0-tests.log
> 0 of 1 test suites (0 of 1 test cases) passed.
For full logs, run 'nix log /nix/store/mcballjp2apqdqfwa3gsz2aqyfn6wc0w-happy-1.20.0.drv'.
```

Adding an overlay to skip tests fixed the problem, while this is not ideal I finally make `my-example-haskell-lib-easy` work on my local by applying the following changes on top of this branch:

```diff
diff --git a/my-example-haskell-lib-easy/flake.lock b/my-example-haskell-lib-easy/flake.lock
index 3b8cd8b..4b03697 100644
--- a/my-example-haskell-lib-easy/flake.lock
+++ b/my-example-haskell-lib-easy/flake.lock
@@ -24,18 +24,14 @@
     },
     "stacklock2nix": {
       "locked": {
-        "lastModified": 1686119819,
-        "narHash": "sha256-iNXW6oqley2vOHtYpxwvruueMsrYSfH0KhYP2pZ5oYI=",
-        "owner": "cdepillabout",
-        "repo": "stacklock2nix",
-        "rev": "8e027606ac4e59498f74024830f8672188ae7bfa",
-        "type": "github"
+        "lastModified": 0,
+        "narHash": "sha256-yPbxmdyUBxZsZLi73PXc0y81hVlnh/AKI1zjAvL9DOI=",
+        "path": "../",
+        "type": "path"
       },
       "original": {
-        "owner": "cdepillabout",
-        "ref": "main",
-        "repo": "stacklock2nix",
-        "type": "github"
+        "path": "../",
+        "type": "path"
       }
     }
   },
diff --git a/my-example-haskell-lib-easy/flake.nix b/my-example-haskell-lib-easy/flake.nix
index f2b4748..b4d5875 100644
--- a/my-example-haskell-lib-easy/flake.nix
+++ b/my-example-haskell-lib-easy/flake.nix
@@ -11,7 +11,7 @@
   # You may also want to lock stacklock2nix to a specific release:
   #
   # inputs.stacklock2nix.url = "github:cdepillabout/stacklock2nix/v1.5.0";
-  inputs.stacklock2nix.url = "github:cdepillabout/stacklock2nix/main";
+  inputs.stacklock2nix.url = "path:../";
 
   # This is a flake reference to Nixpkgs.
   inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
@@ -89,11 +89,9 @@
           #
           # If you are using a very recent Stackage resolver and an old Nixpkgs,
           # it is almost always necessary to override `all-cabal-hashes`.
-          all-cabal-hashes = final.fetchFromGitHub {
-            owner = "commercialhaskell";
-            repo = "all-cabal-hashes";
-            rev = "f3f41d1f11f40be4a0eb6d9fcc3fe5ff62c0f840";
-            sha256 = "sha256-MLF0Vv2RHai3n7b04JeUchQortm+ikuwSjAzAHWvZJs=";
+          all-cabal-hashes = final.fetchurl {
+            url = "https://github.com/commercialhaskell/all-cabal-hashes/archive/f3f41d1f11f40be4a0eb6d9fcc3fe5ff62c0f840.tar.gz";
+            sha256 = "sha256-vYFfZ77fOcOQpAef6VGXlAZBzTe3rjBSS2dDWQQSPUw=";
           };
         };
 
diff --git a/nix/build-support/stacklock2nix/suggestedOverlay.nix b/nix/build-support/stacklock2nix/suggestedOverlay.nix
index 25c571a..dfe6622 100644
--- a/nix/build-support/stacklock2nix/suggestedOverlay.nix
+++ b/nix/build-support/stacklock2nix/suggestedOverlay.nix
@@ -105,6 +105,8 @@ hfinal: hprev: with haskell.lib.compose; {
   # Version constraints on tests are too strict.
   haddock-library = dontCheck hprev.haddock-library;
 
+  happy = dontCheck hprev.happy;
+
   hashable = dontCheck hprev.hashable;
 
   haskeline = dontCheck hprev.haskeline;

```

Once again, I really appreciate all your help with this issue.

**Comment by cdepillabout** [comment]
@sestrella I marked `happy` as `dontCheck` in 777deac, and I added a warning message about case-insensitive filesystems in e8722350711.

I think this should fix up most of your problems.  Thanks a lot for reporting this, and working through this with me!

**Pull request merged**
